const token=new URLSearchParams(location.search).get("token")||sessionStorage.srsToken;
if(token){sessionStorage.srsToken=token;history.replaceState({},"","/")}
const headers={Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
const api=async(path,options={})=>{const r=await fetch(`/api/${path}`,{...options,headers});const j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let cards=[],decks=[];
const answerState=new Map();
const sourceDeckState=new Map();
function metric(label,value){return `<div class="metric"><strong>${value??0}</strong><span>${label}</span></div>`}
function chart(id,data,key,color){const svg=document.querySelector(id),w=700,h=210,max=Math.max(1,...data.map(x=>x[key]||0));if(!data.length){svg.innerHTML='<text x="10" y="30">No data yet</text>';return}const pts=data.map((x,i)=>`${20+i*(660/Math.max(1,data.length-1))},${190-(x[key]||0)*150/max}`).join(" ");svg.innerHTML=`<line x1="20" y1="190" x2="680" y2="190" stroke="#d9d4c7"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`}
async function loadOverview(){const x=await api("overview");const c=x.cards;document.querySelector("#metrics").innerHTML=[["Due",c.due],["Overdue",c.overdue],["Active",c.active],["Draft",c.draft],["Suspended",c.suspended],["Lapses",x.ratings.again]].map(v=>metric(...v)).join("");chart("#trend",x.mastery_trend,"score","#2b715a");chart("#forecast",x.forecast,"due","#c88131");const r=x.ratings,total=Math.max(1,r.reviews||0);document.querySelector("#ratings").innerHTML=["again","hard","good","easy"].map(k=>`<div><span>${k}</span><span class="bar"><i style="width:${100*(r[k]||0)/total}%"></i></span><b>${r[k]||0}</b></div>`).join("");document.querySelector("#weak").innerHTML=x.weak_cards.length?x.weak_cards.map(c=>`<p><b>${esc(c.learning_objective)}</b><br><span class="subtle">${c.lapse_count} lapses · ${c.review_count} reviews</span></p>`).join(""):'<p class="empty">No reviewed cards yet.</p>'}
async function loadDecks(){decks=await api("decks");document.querySelector("#deck-list").innerHTML=decks.map(x=>`<p><b>${esc(x.name)}</b> <span class="pill">${x.status}</span><br><span class="subtle">${x.active_cards} active · ${x.draft_cards} drafts · ${x.due_cards} due</span><br><button data-action="archive" data-deck-id="${esc(x.id)}" data-archived="${x.status!=="archived"}" data-version="${x.version}">${x.status==="archived"?"Restore":"Archive"}</button> <button data-action="export" data-deck-id="${esc(x.id)}" data-deck-name="${esc(x.name)}">Download JSON</button></p>`).join("")||'<p class="empty">No decks yet.</p>'}
function cardHtml(c){const action=c.status==="draft"?`<button data-action="draft" data-card-id="${esc(c.card_id)}" data-status="active">Approve</button><button data-action="draft" data-card-id="${esc(c.card_id)}" data-status="rejected">Reject</button>`:c.status==="active"?`<button data-action="suspend" data-card-id="${esc(c.card_id)}" data-suspended="true" data-version="${c.version}">Suspend</button>`:c.status==="suspended"?`<button data-action="suspend" data-card-id="${esc(c.card_id)}" data-suspended="false" data-version="${c.version}">Restore</button>`:"";const open=answerState.get(c.card_id)?" open":"";return `<div><div class="card-head"><div><b>${esc(c.learning_objective)}</b><div class="subtle">${esc(c.deck_name)} · due ${new Date(c.due_at).toLocaleString()}</div></div><span class="pill">${c.status}</span></div><p>${esc(c.suggested_question)}</p><details data-card-id="${esc(c.card_id)}"${open}><summary>Answer</summary><p>${c.required_concepts.map(esc).join(", ")}</p></details><div class="actions">${action}<button data-action="edit" data-card-id="${esc(c.card_id)}">Edit</button></div></div>`}
function captureAnswerState(){document.querySelectorAll("#card-list details[data-card-id]").forEach(x=>answerState.set(x.dataset.cardId,x.open))}
async function loadCards(){const nextCards=await api(`cards?q=${encodeURIComponent(document.querySelector("#search").value)}&status=${encodeURIComponent(document.querySelector("#status").value)}`);captureAnswerState();const shown=new Set(nextCards.map(c=>c.card_id));for(const id of answerState.keys()){if(!shown.has(id))answerState.delete(id)}cards=nextCards;document.querySelector("#card-list").innerHTML=cards.map(cardHtml).join("")||'<p class="empty">No cards match.</p>'}
function captureSourceDeckState(){document.querySelectorAll("#source-list details[data-deck-id]").forEach(x=>sourceDeckState.set(x.dataset.deckId,x.open))}
function sourceTitle(s){return s.title?s.title.replace(/\s+(?:—|-)\s+intent\s*$/i,""):s.source_uri}
function sourceUriHtml(uri){const value=String(uri??"");try{const parsed=new URL(value);if(parsed.protocol==="http:"||parsed.protocol==="https:"){const label=value.replace(/^https?:\/\//i,"");return `<a href="${esc(value)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`}}catch{}return esc(value)}
function sourceHtml(s){return `<div class="source-snapshot"><b>${esc(sourceTitle(s))}</b><br><code>${sourceUriHtml(s.source_uri)}</code><p>${esc(s.excerpt)}</p></div>`}
async function loadSources(){const sources=await api("sources");captureSourceDeckState();const currentDecks=new Set(decks.map(d=>d.id));for(const id of sourceDeckState.keys()){if(!currentDecks.has(id))sourceDeckState.delete(id)}const grouped=new Map(decks.map(d=>[d.id,[]]));sources.forEach(s=>{if(grouped.has(s.deck_id))grouped.get(s.deck_id).push(s)});document.querySelector("#source-list").innerHTML=decks.map(d=>{const open=sourceDeckState.get(d.id)?" open":"";const items=grouped.get(d.id);return `<details class="source-deck" data-deck-id="${esc(d.id)}"${open}><summary>${esc(d.name)}</summary><div class="source-items">${items.length?items.map(sourceHtml).join(""):'<p class="empty">No source snapshots.</p>'}</div></details>`}).join("")||'<p class="empty">No decks yet.</p>'}
async function loadHistory(){const [s,r]=await Promise.all([api("sessions"),api("reviews")]);document.querySelector("#session-list").innerHTML=s.map(x=>`<p><b>${esc(x.deck_name)}</b> · ${x.reviewed_count} reviews<br><span class="subtle">${new Date(x.started_at).toLocaleString()}</span></p>`).join("")||"No sessions.";document.querySelector("#review-list").innerHTML=r.slice(0,50).map(x=>`<p><b>${Math.round(x.mastery_score*100)}% · ${x.hidden_rating}</b><br>${esc(x.question)}<br><span class="subtle">${new Date(x.reviewed_at).toLocaleString()}</span></p>`).join("")||"No reviews."}
async function refresh(){try{await Promise.all([loadOverview(),loadCards(),loadHistory(),(async()=>{await loadDecks();await loadSources()})()]);document.querySelector("#sync").textContent=`Synced ${new Date().toLocaleTimeString()}`}catch(e){document.querySelector("#sync").textContent=e.message}}
async function draft(id,status){await api("actions/draft-status",{method:"POST",body:JSON.stringify({card_ids:[id],status})});refresh()}
async function suspendCard(id,suspended,version){await api("actions/suspension",{method:"POST",body:JSON.stringify({card_ids:[id],suspended,expected_versions:{[id]:version}})});refresh()}
async function archiveDeck(deck_id,archived,expected_version){await api("actions/archive",{method:"POST",body:JSON.stringify({deck_id,archived,expected_version})});refresh()}
async function exportDeck(id,name){const r=await fetch(`/api/export/${id}`,{headers});if(!r.ok)throw Error((await r.json()).error);const a=document.createElement("a");a.href=URL.createObjectURL(await r.blob());a.download=`${name}.json`;a.click();URL.revokeObjectURL(a.href)}
function editCard(id){const c=cards.find(x=>x.card_id===id),d=document.querySelector("#editor");d.dataset.id=id;document.querySelector("#edit-objective").value=c.learning_objective;document.querySelector("#edit-question").value=c.suggested_question;document.querySelector("#edit-concepts").value=c.required_concepts.join("\n");document.querySelector("#confirm-wrap").style.display=c.status==="active"?"block":"none";document.querySelector("#edit-confirm").checked=false;d.showModal()}
document.querySelector("#card-list").addEventListener("click",e=>{const button=e.target.closest("button[data-action]");if(!button)return;const {action,cardId,status,suspended,version}=button.dataset;if(action==="draft")draft(cardId,status);else if(action==="suspend")suspendCard(cardId,suspended==="true",Number(version));else if(action==="edit")editCard(cardId)});
document.querySelector("#deck-list").addEventListener("click",e=>{const button=e.target.closest("button[data-action]");if(!button)return;const {action,deckId,deckName,archived,version}=button.dataset;if(action==="archive")archiveDeck(deckId,archived==="true",Number(version));else if(action==="export")exportDeck(deckId,deckName)});
document.querySelector("#save").onclick=async e=>{e.preventDefault();const c=cards.find(x=>x.card_id===document.querySelector("#editor").dataset.id),body={card_id:c.card_id,learning_objective:document.querySelector("#edit-objective").value,suggested_question:document.querySelector("#edit-question").value,required_concepts:document.querySelector("#edit-concepts").value.split("\n").filter(Boolean),acceptable_answers:c.acceptable_answers,misconceptions:c.misconceptions,source_ids:c.source_ids};if(c.status==="active"){body.expected_version=c.version;body.confirmed=document.querySelector("#edit-confirm").checked;await api("actions/reset-edit",{method:"POST",body:JSON.stringify(body)})}else if(c.status==="draft"){await api("actions/draft-edit",{method:"POST",body:JSON.stringify(body)})}document.querySelector("#editor").close();refresh()};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector(`#${b.dataset.view}`).classList.add("active")});
document.querySelector("#refresh").onclick=refresh;document.querySelector("#search").oninput=()=>{clearTimeout(window.st);window.st=setTimeout(loadCards,250)};document.querySelector("#status").onchange=loadCards;
async function bulk(status){const ids=cards.filter(x=>x.status==="draft").map(x=>x.card_id);if(ids.length){await api("actions/draft-status",{method:"POST",body:JSON.stringify({card_ids:ids,status})});refresh()}}
document.querySelector("#bulk-approve").onclick=()=>bulk("active");document.querySelector("#bulk-reject").onclick=()=>bulk("rejected");
refresh();setInterval(refresh,5000);
